version: '3.8'

services:
  web:
    build: .
    container_name: flask-postgres-app-web
    ports:
      - "5050:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/flask_db
      - FLASK_ENV=development
    volumes:
      - ./app:/app
    restart: unless-stopped
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: flask-postgres-app-db
    environment:
       POSTGRES_USER=postgres
       POSTGRES_PASSWORD=postgres
       POSTGRES_DB=flask_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

volumes:
  pgdata:
    name: flask_postgres_data

networks:
  app-network:
